### ISSUE TITLE
Blade support

### ISSUE THREAD

**Issue by Ljay-ru** [jesusOmar/one-dark-phpstorm#11]
Hello!

Is it possible to add more beautiful support for blade templates?

Now it looks a bit disappointing.

**Comment by jesusOmar** [comment]
Not sure what you are asking for... currently blade displays mainly the same on atom and phpStorm, any differences seem to be limitations with the IntelliJ environment aka phpStorm

<img width="1033" alt="preferences_and_index_blade_php_-_time-lord_-____code_time-lord__-_phpstorm_2017_2_eap" src="https://user-images.githubusercontent.com/377084/28343873-89a16172-6bed-11e7-9e39-5b955aa7a155.png">

<img width="1052" alt="item-0_and_item-0_and_applevpnextra_and_applebluetoothextra_and_applevolumeextra" src="https://user-images.githubusercontent.com/377084/28343883-9d057c62-6bed-11e7-8e1f-067639d73f6c.png">
