### ISSUE TITLE
Bad configuration ?

### ISSUE THREAD

**Issue by Extazx2** [jesusOmar/one-dark-phpstorm#12]
Hello, i downloaded this one, because i found that javascript syntax color sucks on phpstorm, but it's kinda same now, and i think there is an issue.

see an exemple here : https://gyazo.com/72fca090666d3901402c0e035885e858

**Comment by jesusOmar** [comment]
This should be a bit better...

PhpStorm:
<img width="1026" alt="preferences_and_index_blade_php_-_time-lord_-____code_time-lord__-_phpstorm_2017_2_eap_and_failed_to_activate_the_bracket-matcher_package_ _issue__281_ _atom_bracket-matcher" src="https://user-images.githubusercontent.com/377084/28346704-b5c3c0ac-6c00-11e7-8c9b-11ed131f616f.png">

Atom:
<img width="752" alt="untitled_ ___code_time-lord" src="https://user-images.githubusercontent.com/377084/28346765-fca5d1fe-6c00-11e7-8b28-b1b73c5e949e.png">
