### ISSUE TITLE
Dull Colors

### ISSUE THREAD

**Issue by TwisterMc** [jesusOmar/one-dark-phpstorm#2]
The One Dark theme for Atom has much brighter color pallet. Will the colors be updated to correspond a bit more with Atom's colors?

**Comment by jesusOmar** [comment]
@TwisterMc Is this with PHPStorm 9.5 EAP? I've noticed that the colors are wrong with that version of PHPStorm but I haven't had the time to update the theme to work with it.

**Comment by TwisterMc** [comment]
PhpStorm 9.0.2 vs Atom 1.0.19

**Comment by johannes-z** [comment]
Even in the preview screenshots the colors are duller than in Atom. 

On an unrelated side note: The font settings seem to be kinda off (at least for PHPStorm 9.0.2). I couldn't get it to look like in the preview screenshot, I even tried using Fira Mono (Regular and Medium).

**Comment by jesusOmar** [comment]
Ok I'll take a closer look as soon as I can... has been a crazy week =/

**Comment by TwisterMc** [comment]
No worries. Appreciate the work you've done so far!

**Comment by jesusOmar** [comment]
@TwisterMc I've done a small update... this is what it looks like next to the atom theme on my current setup. Let me know if you see something different.

<img width="1781" alt="side_by_side" src="https://cloud.githubusercontent.com/assets/377084/10613178/2080dcf2-7722-11e5-9ac2-ab0621d40657.png">

**Comment by TwisterMc** [comment]
Looks great. Thanks!
