### ISSUE TITLE
PHPstorm 10 compat

### ISSUE THREAD

**Issue by iilei** [jesusOmar/one-dark-phpstorm#3]
Thank you for this beautiful color scheme!

With version 10 there is no `colors` folder :cry: – do you know how to use this theme with the latest version of PHPStorm?

**Comment by luis-rodriguez** [comment]
I was about to write this issue. Thanks!

**Comment by jesusOmar** [comment]
I've been using the Material Theme so I hadn't noticed... but I will investigate as soon as possible.

**Comment by luis-rodriguez** [comment]
I made a PR with some Javascript enhancements... PHP part is now working also :)

**Comment by jesusOmar** [comment]
@iilei I believe that if the colors folder is missing from ~/Library/Preferences/WebIde100 on Mac you should be able to create it and place the color scheme there. I'm merging the JS enhancements and everything seems to work for me on PHPStorm 10.0.3 can you confirm?

**Comment by bIbI4k0** [comment]
Not working on phpstorm9, print this error:
Cannot read scheme OneDark.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

**Comment by bIbI4k0** [comment]
To fix this, set version value in color schema file 141 instead 142. 
<scheme name="One Dark" version="141" parent_scheme="Default">

Sorry for bad english.

**Comment by iilei** [comment]
@jesusOmar works like a charm! Thanks :+1:

**Comment by Egorby** [comment]
Amazing!!!! Many thanks!
