### ISSUE TITLE
CSS color previews are hidden

### ISSUE THREAD

**Issue by mariomka** [jesusOmar/one-dark-phpstorm#8]
CSS color previews are hidden. I have checked option "Show CSS color preview icon in gutter" at Preferences > Editor > General > Appearance. Color preview are shown if I change the color scheme by another one.

**Comment by jesusOmar** [comment]
@mariomka this is a simple setting inside phpStorm, you can enable it via "Editor > General > Appearance"

<img width="1019" alt="preferences" src="https://cloud.githubusercontent.com/assets/377084/14431691/cec250b2-ffd4-11e5-99ec-061df2703876.png">

**Comment by mariomka** [comment]
It is enabled...

> I have checked option "Show CSS color preview icon in gutter" at Preferences > Editor > General > Appearance. 

![captura de pantalla 2016-04-11 a las 17 23 45](https://cloud.githubusercontent.com/assets/1822472/14432394/48acc8f0-000a-11e6-8283-edcb273ec7f8.png)

Working with another one theme, like solarized:

![captura de pantalla 2016-04-11 a las 17 25 30](https://cloud.githubusercontent.com/assets/1822472/14432448/859e9ae0-000a-11e6-872d-ba8e82942ab4.png)

**Comment by jesusOmar** [comment]
@mariomka weird, I'll check again but I could swear I enabled it on mine and they turned on right away.

**Comment by jesusOmar** [comment]
@mariomka I just pushed a small change, but honestly I'm not sure what's happening here. I can't get my version of PhpStorm (2016.1) to not show the previews in the gutter. Can you try it and get back to me?

**Comment by mariomka** [comment]
Theme updated and same behaviour.

**Comment by mariomka** [comment]
I found the "problem"... Is about the font size, I think is a Phpstorm bug. Setting the font size between 12-14 color preview works (with Menlo, depends of font).

**Comment by mariomka** [comment]
It will be fixed in next version 2016.1.1
Related: https://youtrack.jetbrains.com/issue/IDEA-151485#comment=27-1372064

**Comment by FrankFang** [comment]
The bug accurs on WebStorm ver 2019.3
